_maps/map_files/MiniStation/MiniStation.dmm, _maps/shuttles/emergency_hugcage.dmm
So, I noticed Ministation wasn't passing linters.
*"Why?"* I thought to myself - surely, it was just an issue from having it swap codebases and could be fixed up really quickly and easily.
Ahah.
Ahhahhah.
And thus, this PR. A lot of broken features, unused variables, and non-directionals no more!
=> Ministation Varedit Pass (+ Bonus Hugcage One)

code/modules/mob/living/carbon/human/human_update_icons.dm
Like it says above. This will let digi outfit variations work again since they were apparently disabled.
Cause having broken sprites is super dumb.
:cl:
fix: re-enabled digi uniform variants.
/:cl:
=> Re-enables Digi uniforms

code/controllers/configuration/entries/general.dm, code/controllers/subsystem/ticker.dm, code/modules/admin/verbs/server.dm, config/config.txt
Pre-game lobby doesn't proceed to setup until there are players connected and ready. Can be overridden in config and with the admin commands Delay Pre-Game and Start-Now.
- No point in starting the processing if nobody is around to play.
- If a server is empty for whatever reason before a player connects, they aren't greeted with a game that's been running for hours, no power, air depleted etc.
https://user-images.githubusercontent.com/83487515/236703589-b67cb2b0-4695-45cb-bac2-f879702eb159.mp4
:cl: LT3
config: Round will wait in the pre-game lobby if nobody is flagged ready
/:cl:
=> It takes two players for

code/game/objects/items/airlock_painter.dm, code/modules/mob/living/silicon/robot/robot_model.dm
Was a request by a borg player on the dicord. Seemed to make enough sense for an engineer borg to be able to paint doors and floors.  So here it is.
I kind of winged it on the flavor text though, so feel free to change that up if you have something better in mind.
More tools for el' borgos.
:cl:
add: New cyborg painting tool assigned to engineering borgs.
/:cl:
=> Engi borg Painting tool expansion

_maps/map_files/MiniStation/MiniStation.dmm
Adds cargo, engi, and atmos drobes to Ministation. Replaces a table, an emergency locker, and an electrical locker respectively.
Cargodrobe provides mailbags, and engidrobe provides several useful items such as welding hard hats. Atmosdrobe is really only there to round out the engidrobe, but there's already an electrical supplies locker and a stack of insulated gloves in the department, so I doubt the replaced locker will be missed.
:cl:
add: Added engi, atmos, and cargo Drobes to Ministation.
/:cl:
=> Ministation drobes

code/controllers/subsystem/ticker.dm, packages/autotransfer/autotransfer.dm
:cl: LT3
fix: Autotransfer vote should not fire immediately after a delayed round start
/:cl:
=> Autotransfer uses time from ticker

code/modules/reagents/withdrawal/generic_addictions.dm, overrides/code/modules/reagents/withdrawal/generic_addictions.dm
Nerfs the withdrawal effects of nicotine.
I know I've bitched about this for years but here it finally is.
To address an Effigy specific issue, I've blocked out the old code in favor of the override code. Turns out we were actually double-dipping on the side effects and coughing. Explains why earlier, I had mentioned during a live round how I had like 20 coughs in a handful of seconds.
Additionally, I've straight up removed the coughing and the jitteriness from the remaining version.
However, gives a slight buff to the chance of getting hit with the stamina loss side effects.
Well for an RP server, it's just annoying. When I or others who use smokes stop for an RP scene you end up clogging up the chat log with "So-n-So coughs" messages. Additionally, the jitteriness fucks with layering …
=> Nicotine withdrawal nerf

_maps/map_files/FoxHoleStation/foxholestation.dmm
Scatters some directional signs around FoxHole, because 99.9% Of Spacemen Fail The Navigate Verb Test (LOWER RESULT RATES THAN ECTO SNIFFERS?? ALMOST DIED AT 3 AM)
:cl:
qol: Foxhole has received navigational signs.
/:cl:
=> Foxhole And The Signening

code/modules/mob/living/carbon/life.dm, packages/liquids/liquid_systems/liquid_effect.dm
Some liquid fixes to preamble us for the big ones, like whatever is fucked with immutable liquids and Multi-Z and mayybe the monkeliquids optimizations.
:cl: vinylspiders, out-of-phaze for Skyrat
fix: drowning in liquid that is not water will now give the appropriate message based on what kind of liquid it is
fix: Liquid overlays now properly clear.
/:cl:
=> Ports SR PRS 21351 and 21705

_maps/map_files/FoxHoleStation/foxholestation.dmm
Lookit mapdiffbot for a quick glance at all the changes, I am just... *bewildered* by how these issues were even brought to my attention in the first place.
I have left out two suggested changes, and my reasons why are as follows:
- The centre table being laid out this way actually encompasses just that *teeny* bit more table space than a traditional 2x6 if you use the corners for the actual tablework. These corners are now marked roundstart. It also just straight up is less bland.
- Botany still has to walk to deliver produce. This needs either a funky solution or a service remap to really be addressed.
As a bonus, actually de-scuffs the service disposals.
:cl:
qol: Foxhole's Kitchen has been touched up.
/:cl:
=> Foxhole Kitchen Rework

code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm, code/modules/antagonists/changeling/changeling.dm, code/modules/antagonists/traitor/datum_traitor.dm, code/modules/events/creep_awakening.dm
:cl:
del: Obsessed has been disabled, minus admin fuckery.
del: Traitors/Lings will no longer get full assassination objectives. Progtot can still roll secondary assassinations.
/:cl:
=> [REQ] Disables Tot/Ling Primary Objective Assassination, Obsessed

tgui/packages/tgui/interfaces/InteractionMenu.tsx
Part 1, i need to recategorize  the verbs themselves next and then move onto officially adding more
I dont like having to scroll a mile to just accidentally sit on someone's face, this categorizes everything and shrinks them down into manigable categories based on the action. This screenshot isnt final for categories, just an example.
Secks
:cl:
qol: makes lewding verbs not be a CVS receipt
/:cl:
=> Interactions Menu modernization

code/modules/asset_cache/assets/rcd.dm, packages/gfx/airlock.dm
Updates the airlock assembly to use the new sprites instead of the old. 
Additionally updates the RCD selector to show the new airlock sprites instead of the old ones as well.
Bad old 
New good
RCD:
resolves #197 
:cl:
fix: Updated door_assembly sprites
fix: Updated RCD selector airlock sprites
/:cl:
=> Updates airlock assembly sprites

code/modules/mob/living/living.dm
As was noticed last round. If you stood up you retained the lay down pixel shift of -6 pixels.
After some debugging I realized it was just two procs firing off in the incorrect order.
Don't have to use pixel shifting to fix the broken pixel shift.
:cl:
fix: Fixed retaining lay down pixel shift upon standing.
/:cl:
=> Fixes pixel shift on stand up

code/modules/mob/living/living_say.dm
Whispers won't carry obstructed with asterisks if it's a headset message.
:cl: LT3
code: Headset messages won't carry distance obstructed with asterisks
/:cl:
=> Radio whispers don't carry distance

_maps/map_files/FoxHoleStation/foxholestation.dmm, _maps/map_files/MiniStation/MiniStation.dmm
Updatepaths fucked these up on Foxhole and Mini. Ugh.
This fixes. All of that.
:cl:
fix: Stripes are no longer pointing the wrong way on foxhole.
/:cl:
=> [MDB Ignore] Fixes Decals

code/game/sound.dm, local/code/modules/client/preferences/erp_preferences.dm, packages/lewd/lewd_arousal/climax.dm, tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/skyrat/erp_preferences.tsx
Adds a toggle to let people locally disable the climax sound effect. Also adds a tagging system to the playsound() proc in sound.dm which lets you tag a proc call. Future PRs could include other tags such as toy noises.
The doomguy climax sound currently has no toggle and is unpleasant.
Adds more user controls to their prefs
:cl:
add: Toggle option for climax noise
add: tagging system for playsound() proc
/:cl:
=> Adds toggle for climax sound and tagging system for playsound()

packages/customization/modules/client/augment/limbs.dm, packages/customization/modules/surgery/bodyparts/parts.dm, packages/customization/modules/surgery/bodyparts/robot_bodyparts.dm, tgstation.dme
Adds the ability to forsake a limb for two quirk points. @lessthnthree , inadvertently creates more work for #264 (sorry!)
*The way this works behind the scene is by making a new limb subtype that quickly detaches itself and qdels itself upon being applied. I wasn't in the mood to entirely refactor augments to account for forsaking limbs, but that would be preferable in the long run.*
Same reason plasmaman limbs were - more open character design. Even if I imagine some goofiness will unfold thanks to someone not thinking their choices through.
:cl:
add: You can now choose to forsake a limb in exchange for two quirk points, in the augments menu.
/:cl:
=> [Bounty] Adds The Option For Missing A Limb To The Prosthetics Menu

code/modules/mob/living/silicon/robot/robot_model.dm
Gives mining borgs a kinetic crusher!
They used to have these, but then it got removed, and honestly that's a tragedy.  Crushers let them have a slightly easier time fighting fauna, and lets them butcher corpses for more ore.  No more dragging dead creatures up to someone like some sort of cat!
https://github.com/effigy-se/effigy-se/assets/46330016/9ee4d846-5648-4b27-90c9-6767735b1878
:cl:
add: Adds a kinetic crusher to mining cyborgs.
/:cl:
=> Mining borgs can CRUSH all of lavaland again

code/modules/mob/living/carbon/carbon_defense.dm
The order of operations on this one were wrong. Oops.
:cl:
fix: Excitable now applies on headpat instead of tailpull, as was intended. I would've had it apply on both but I am absolutely not making a new proc just for that when we're still in customization DEFCON 1. You wouldn't either!
/:cl:
=> Excitable now applies on headpat instead of tailpull

local/code/modules/admin/verbs/adminhelp.dm
Strip hrefs before sending to the API. We don't need them.
=> Sanitize adminhelp interactions before sending to Effigy API

_maps/map_files/FoxHoleStation/foxholestation.dmm
:cl:
fix: Foxhole no longer has a (now redundant) relay on the second deck.
/:cl:
=> Foxhole - Oops, Removes the Redundant Station Relay

_maps/map_files/FoxHoleStation/foxholestation.dmm, _maps/map_files/MiniStation/MiniStation.dmm
Catches us up with the whole armory spawners thing, oops.
:cl:
fix: A lot of navigate destinations have been descuffed on Ministation. Not that anyone has ever used them.
/:cl:
=> Those Dagnabbib Armory Spawners!

_maps/foxholestation.json, code/modules/reagents/reagent_containers.dm, local/code/datums/loadouts/loadout_datum_toys.dm, local/code/game/machinery/cryopod.dm, local/code/modules/lewd/lewd_arousal/climax.dm, local/code/modules/lewd/lewd_machinery/milking_machine.dm, local/code/modules/lewd/lewd_organs/_genital.dm, local/code/modules/lewd/lewd_quirks.dm, local/code/modules/liquids/liquid_systems/liquid_plumbers.dm, local/code/modules/liquids/liquid_systems/liquid_turf.dm, local/code/modules/mob/dead/new_player/sprite_accessories/synthliz.dm, local/code/modules/modular_implants/nif_persistence.dm, local/code/modules/modular_implants/nifsoft_catalog.dm, local/code/modules/modular_implants/nifsofts.dm
Relevant PRs outlined in commit names. Changelog is an amalgam of all relevant with my own changes at the end.
:cl: vinylspiders, Iamgoofball, VastKilleroOm for Skyrat 13, unit0016
fix: fixed an issue that was causing climaxes to not complete if you possessed testicles, leading to being permanently horny in some cases
fix: fixes some runtimes with the milking machine
fix: Sadism quirk will now wait until the climax moodlet is gone before starting to add more arousal
fix: Buffs spacemen refractory period to reduce audio spam problems for players walking past dorms
fix: fixed a few things [Maintainer note: Synthliz tail now can wag again. Unsure why this was left default SR-side asides from language barrier.]
fix: fixed a bug with the liquid output pump's height regulator that was causing …
=> Reintegrates Shark Plushie Into The Loadout + Batch Of Important Module Fixes

code/__DEFINES/subsystems.dm, code/__HELPERS/logging/_logging.dm, code/_globalvars/_effigy/config.dm, code/controllers/subsystem/dbcore.dm, config/effigy_config.txt
Removes the SQL game logging setup used by Skyrat
While we used to use it, we have our own logging method now.
:cl: LT3
server: Removed Skyrat related logging code
/:cl:
=> Remove dormant SQL game logging

code/modules/client/preferences.dm, local/code/datums/dna.dm, local/code/modules/client/preferences.dm
:cl: CliffracerX
fix: mutantcolors are being pulled from your features dna again, no more pink feathers!
/:cl:
=> [PORT] Fixes Quickspawn/SimpleTF/genetics eating mutcols

code/modules/security_levels/keycard_authentication.dm, local/code/controllers/subsystem/job.dm
If the server pop is below the lowpop number in config, round starts with maint access enabled.
:cl: LT3
qol: Maintenance access now enabled on lowpop rounds
/:cl:
=> lowpop maint access

code/modules/mob/living/carbon/life.dm
Liquid suffocation will now handle suffocation same way everything else does, in `check_breath()`. It would be nice in the future to add some sort of proc for breathing from a liquid turf itself (which would enable being able to breathe liquid in space, as well as making specific liquids not breathable). 
But for now there's this.
Fixes a bug
<details>
<summary>Drowning suffocation</summary>
</details>
:cl: vinylspiders
fix: the suffocation moodlet will now be cleared when you stop drowning in liquid
/:cl:
=> [PORT] Fixes suffocation moodlet from liquids not being cleared after you stop drowning

code/datums/station_traits/positive_traits.dm
Git must have accidentally overwrote incoming changes with local ones because the line looked similar. 
fix great cybers cool
:cl:
fix: Bitrunners now partake in cybernetic revolutions again.
/:cl:
=> Add bitrunners back to cybernetic revolutions again

local/code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
This vomit call hasn't been updated since the vomit refactor got merged
fix good vomit not good
:cl:
fix: Organic creatures will now vomit correctly when drinking synth drinks again.
/:cl:
=> Fix a bad vomit call in synthanol mob life

local/code/modules/mob/living/carbon/human/species_types/synthetic.dm
Rewrites a bit of code that handles applying additional features. This code smells and has nothing to do with effigy itself, I think. I made it smell worse now :)
Fixes #373
fix good word better
:cl:
fix: Synth lizard digitigrade legs should now be colored like the rest of the body.
/:cl:
=> Fixes synth lizard digitigrade legs not having the color applied correctly

_maps/templates/automapper/icebox/icebox_broadcast_studio.dmm
Duplicate pipes under the door to the icebox broadcasting studio caused mapping failures
less error more good
:cl:
fix: Removes duplicate pipes in icebox broadcasting studio.
/:cl:
=> Remove duplicate pipes in icebox broadcasting studio

local/code/modules/client/preferences/_preference.dm, local/code/modules/client/preferences/mutant_parts.dm
As quoted by Julius Caesar himself: 
https://github.com/effigy-se/effigy-se/blob/3933e78f79ab495b19cdffd5204f5dc1a6c6c3fa/local/code/modules/client/preferences/mutant_parts.dm#L49
Doesn't make sense for it to constantly fail CI then
less mean circle more do
nothing playerfacing
=> Removes empty `icon_for` implementation from unused body markings preferences

code/modules/antagonists/abductor/abductor_structures.dm
Alien optables override a signal from their parent, which leads to `chill_out` not being called
Fixes #411
numbing good less pain
:cl:
fix: Alien operating tables will now numb people properly again.
/:cl:
=> Fix alien optable not numbing patients

_maps/map_files/RimPoint/RimPoint.dmm
:cl:
fix: You can access the MortiDrobe again.
/:cl:
=> Rimpoint Morgue Fix

_maps/map_files/FoxHoleStation/foxholestation.dmm, _maps/map_files/RimPoint/RimPoint.dmm
Updates Foxhole and Rimpoint to have parity with other maps' cargo - IE, bandages.
There also appears to be an issue with railings but I think that's.. uhh.
Going to be addressed upstream? Maybe?
=> TG Update - Cargo Parity, Railing Fixes

code/modules/research/stock_parts.dm
This edit was made entirely because we didn't want to adapt but we adapted anyways because we didn't actually edit the names in the lathes. lol
let's not repeat this, please.
:cl:
fix: Servos are now no longer occasionally called Manipulators. Please consume your scheduled corn syrup as normal.
/:cl:
=> Kills some undocumented non-modular changes (Servos)

local/code/datums/loadouts/loadout_datum_toys.dm, local/code/game/objects/items/dice.dm, tgstation.dme
adds a lore accurate dice to loadouts
its hilarious
:cl:
add: Added a weighted d20 to player loadouts. It's not favorable.
/:cl:
=> Add the lore-accurate weighted dice

local/code/controllers/subsystem/effigy/whitelist.dm
the account id is properly converted into a number now with error checking, fixing the discord command
also fixes a runtime that happens in the insert player proc that occurs when the db query returns false (when an admin advanced proccall is found to have happened)
:cl:
admin: The whitelist discord command should work properly again.
/:cl:
=> Fix whitelist discord command

code/__DEFINES/_effigy/medical_defines.dm, code/game/objects/items/defib.dm, local/code/game/machinery/dna_fixer.dm, local/code/game/machinery/washing_machine.dm, local/code/game/objects/items/defib.dm, local/code/modules/client/augment/limbs.dm, local/code/modules/client/preferences/middleware/limbs_and_markings.dm, local/code/modules/clothing/suits/misc.dm, local/code/modules/modular_implants/nifs.dm, local/code/modules/modular_implants/nifsofts/dorms.dm, local/code/modules/modular_implants/nifsofts/hypnosis.dm, local/code/modules/research/medical_designs.dm, local/code/modules/research/techweb/all_nodes.dm, local/code/modules/surgery/robot_chassis_restoration.dm, local/code/modules/surgery/robot_healing.dm, tgstation.dme
Synth QOL, Renaming, Blahblah.
:cl: nikothedude, softcerv, honkpocket for Skyrat 13
balance: Synth tend wounds repeatable step now takes 2.5 seconds from 1
balance: 2 new synth tend wounds upgrades available to research
fix: Synth tend wounds now gives proper feedback
balance: Defibrilators now EMP synths and apply a temporary brain trauma for 90 seconds to them
balance: Synth revival surgery time and steps vastly reduced/streamlined
fix: the ghost role NIF boxes now contain the Purpura Eye NIFSoft
qol: SAD patients can now reject the treatment at the last step, preventing any changes from being made
fix: Chest/Heads can now be augmented in the augment menu
add: You can now buckle yourself to washing machines! This serves no practical purpose except for FUN TIMES.
fix: fixed ghost …
=> Module Mirror Maintenance

code/datums/ruins/icemoon.dm, code/datums/ruins/lavaland.dm, code/datums/ruins/space.dm
Okay, so. This PR's gonna have some fallout assuming some config tweaks aren't enabled on the box.
This re-enables every /tg/ ruin accidentally disabled by #3. Only one of these isn't a ghostrole.
Whilst we've been *avoiding* letting people play ghostroles as to (rightfully) keep our pop from being split up so early, we've already had a few people remaking their statics on assumption (and proclamations by some of our own otherwise), and it's my grand duty as ~~ruby miller~~ a maintainer to cede to the tiniest bit of pressure and open the flood gates. Codewise only. Config it's anyone's game.
One problem, if we're actually going to canonize having ghostroles this early instead of disabling these config-side until we need to have them.
We don't have the code for handling prefs on ghostroles …
=> Opens The Gates Of Hades: Part One, Just The Ruin Datums

local/code/modules/modular_implants/nifsofts/soulcatcher.dm, local/code/modules/modular_implants/soulcatcher/soulcatcher_component.dm
Race condition. In the parent `/datum/nifsoft/New()` it calls `update_theme()` which expects the `linked_soulcatcher` var to be set, but it doesn't get set until the end of `/datum/nifsoft/soulcatcher/New()`. So it runtimes.
This fixes that.
Also fixes a bonus runtime:
Less runtiming is good
<details>
<summary>Screenshots/Videos</summary>
</details>
Nothing really significantly player facing I don't think?
=> [PORT] Fixes a nif related runtime with update_theme

local/code/modules/mob/living/emotes/emotes.dm
Blocking flipping was accidentally ported from Skyrat. Fixes that!
Our players have the freedom to flip if they so choose.
:cl: LT3
balance: The shackles preventing you from flipping have been removed
/:cl:
=> Enable flipping

code/__DEFINES/transport.dm
Due to our run speed, adjusts the tram signal timing so that you can actually cross the tracks on yellow without guaranteed death.
:cl: LT3
balance: Tram crossing signals adjusted to match run speed
/:cl:
=> Give the poor crew a chance to beat the tram

local/code/modules/liquids/liquid_systems/liquid_controller.dm, local/code/modules/liquids/liquid_systems/liquid_effect.dm, local/code/modules/liquids/ocean_turfs.dm
This PR creates an extra list of liquid overlays with modified planes that match the requesting turf's Z-level. Hopefully this fixes this stupid bleedthrough error once and for all. I sat on this idea for weeks unsure if it would work until Lemon basically confirmed that this idea has been tried and tested and pointing me to gas overlay code.
bleedthrough sucks for ocean maps
Fixes #213 
:cl:
fix: Water from levels below will no longer appear as if they were above the current level's turf.
/:cl:
=> Hopefully fix liquid bleedthrough, once and for all

local/code/datums/level_datums.dm, tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss, tgui/packages/tgui-panel/styles/tgchat/chat-light.scss
- Adjusts the announcement padding/margins for our custom fonts.
- Sets default announcement color back to grey.
- Color matches TG https://github.com/tgstation/tgstation/pull/79315 for the most part
- Removes old Effigy specific CSS that's now included upstream
:cl: LT3
image: Announcement tweaks using new CSS
/:cl:
=> Effigy CSS adjustments

local/code/modules/client/preferences/erp_preferences.dm, local/code/modules/mob/living/examine_tgui.dm, tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/skyrat/genitals.tsx
- Removes NC and vore preferences from character prefs
- Put 'mechanical' in brackets to appear after ERP Status
- Set ERP Status default value to 'No'
We don't allow NC and vore isn't in the codebase, simplifying this to a single prefs box for players. ERP pref should default to No because it's entirely opt-in.
:cl: LT3
del: Removed NC and vore preference options
code: ERP Status now defaults to No instead of Ask
/:cl:
=> Update player prefs menu options

code/__DEFINES/_effigy/loadouts.dm, local/code/datums/loadout_manager.dm, local/code/datums/loadouts/_loadout_datum.dm, local/code/datums/loadouts/loadout_datum_pocket.dm, local/code/datums/loadouts/loadout_datum_toys.dm, local/code/game/atoms.dm, local/code/game/objects/items/plushes.dm, local/code/modules/client/loadout_outfit_helpers.dm, local/code/modules/clothing/clothing_variation_overrides/suit.dm, local/code/modules/clothing/under/jobs/medical.dm, local/code/modules/modular_implants/soulcatcher/soulcatcher_tgui.dm, tgstation.dme
:cl: Iamgoofball, sqnztb, honkpocket, vinylspiders, Plum-but-gayer for Skyrat 13
qol: You can now rename and describe any loadout item, not just plushies.
fix: soulcatchers' edit name button correctly displays the host name
fix: Fixes more unintended taur clothing cropping.
fix: fixed a bug where loadout plushes would sometimes have their custom descriptions reset under certain conditions
fix: fixes some of the runtimes in the loadout system caused by job/species restricted items
add: Bureaucrats rejoice! Clipboards and folders are now available in the loadout menu, under the 'Other' tab.
/:cl:
=> More /local/ Parity

local/code/datums/loadouts/loadout_datum_suit.dm, local/code/game/objects/effects/spawners/random/clothing.dm, local/code/modules/clothing/clothing_variation_overrides/suit.dm, local/code/modules/clothing/suits/labcoat.dm, local/code/modules/mob/dead/new_player/sprite_accessories/genitals.dm, local/code/modules/vending/wardrobes.dm
Removes labcoat override for digi sprite until it can be converted to GAGS.
:cl: LT3
fix: Labcoats should no longer be a counterstrike texture
/:cl:
=> Remove labcoats override

tgui/packages/tgui-panel/game/constants.ts
Increases the TGUI reconnect threshold
The server takes more than 20 seconds to reboot, so this will make the auto reconnect on round restart more consistent.
:cl: LT3
config: TGUI reconnect threshold time increased
/:cl:
=> Increase TGUI timeout tolerance

code/datums/chatmessage.dm
:cl: LT3
fix: Obscured players no longer use preference runechat color
/:cl:
=> Remove preference chat color for obscured players

local/code/controllers/subsystem/autotransfer.dm
:cl: LT3
fix: Autotransfer should no longer call a vote as soon as the shift starts
/:cl:
=> Fix autotransfer calling a vote when a delayed round starts

local/code/modules/mob/living/human/species.dm, tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/base.tsx
TG 81018
What it says on the tin. The entire bottom half of the prefs was not updating on switching character slots.
We need to use the old hook here because it needs the key to differentiate the active slot.
Bugfix for a kind of serious issue for downstreams, not so much here because there aren't really any text fields being used as features.
:cl: vinylspiders
fix: fixes features not updating when changing character slots
/:cl:
=> Fixes features not updating when changing character slots

_maps/map_files/FoxHoleStation/foxholestation.dmm, _maps/map_files/RimPoint/RimPoint.dmm
Fixes FoxHole and Rimpoint to be at par with Delta\* when it comes to ArcMining.
\*Both maps don't have the space for a premade setup preallocated and I'd rather let it be sandboxed like it is there tbh
Also fixes #673 and adds a new cute little chapel office there to replace the old one
Map parity good, cozy good
:cl:
add: Rimpoint now has a crematorium. Oops?
/:cl:
=> FoxHole + Rimpoint: Arcmining Patch, Cremator

_maps/map_files/FoxHoleStation/foxholestation.dmm, _maps/map_files/RimPoint/RimPoint.dmm
Supercedes #688 as the rest of the PR *should* already be addressed. In theory. Also makes it possible to grab the mining points out of the machines on both. Lol
:cl:
add: Foxhole and Rimpoint now have pre-set rigs for boulder mining.
/:cl:
=> Foxhole + Rimpoint - Arcmining Rigs

local/code/game/machinery/doors/airlock_override.dm
🆑 LT3
fix: Fixed ineligible airlocks from receiving engineering override when activated from the communications console
/:cl:
=> Fix early return in airlock engineering override

local/code/modules/client/preferences/headshot.dm
Adds F-List and Effigy CDN to the allowed headshots regex
:cl: LT3
code: F-List and Effigy CDN can be used for headshot links
/:cl:
=> Update headshot regex filter

local/code/modules/client/preferences/headshot.dm, tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/skyrat/headshot.tsx
:cl:
add: Catbox, Imgbox, and F-List can now be used for headshot photos
/:cl:
=> Update headshot regex

_maps/effigy/map_files/FoxHoleStation/foxholestation.dmm, _maps/effigy/map_files/RimPoint/RimPoint.dmm, _maps/effigy/map_files/SigmaOctantis/SigmaOctantis.dmm
Every cargochat console has been moved around ever-so-slightly to accommodate losing it's twin.
=> Cargochat Console Fixes

_maps/effigy/RandomRuins/OceanRuins/ocean_bubble_rally.dmm, _maps/effigy/map_files/FoxHoleStation/foxholestation.dmm, _maps/effigy/map_files/RimPoint/RimPoint.dmm, _maps/effigy/map_files/SigmaOctantis/SigmaOctantis.dmm, _maps/effigy/map_files/generic/CentCom_z2_effigy.dmm, _maps/effigy/templates/automapper/icebox/icebox_cryo.dmm, _maps/effigy/templates/automapper/metastation/metastation_cryo.dmm, code/__DEFINES/_effigy/jobs.dm, code/modules/jobs/job_types/_job.dm, code/modules/mob/dead/new_player/new_player.dm, local/code/controllers/subsystem/job.dm, local/code/game/machinery/cryopod.dm, local/code/game/objects/effects/landmarks.dm, local/code/modules/client/preferences/latejoin_location.dm, tgstation.dme, tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/effigy/latejoin_location.tsx
You ever notice that in spite of technical feature parity (and surpassment) in regards to the Interlink; you still had to go out of you way to catch the shuttle there? That wasn't actually the intent; it was a gameplay concession for the "short-term". But then I remembered that certain Polaris forks actually created a preference that let you choose your spawnpoint, one thing led to another; a few rock-against-wall rewrites later; and now we have this.
tl;dr, there is now a new per-character preference to opt into spawning at the Interlink or Cryo when you latejoin; making both actually interwoven with their intended purposes again. Oorah.
Draft while I check some hyper-specific edgecases.
Stops a few features from feeling disjointed; and adds a opt-in parity feature for those that want …
=> Latejoin Spawnpoint Preference - Marries Cryo & The Interlink into the Broader Ecosystem

_maps/effigy/map_files/SigmaOctantis/SigmaOctantis.dmm, local/code/game/machinery/doors/firedoor.dm
:cl:
balance: It should be significantly harder for Greytide to flood the entire first deck of Sigma Octantis.
/:cl:
=> Sigma Octantis Firedoor Audit

_maps/effigy/map_files/SigmaOctantis/SigmaOctantis.dmm
:cl:
fix: Following the mysterious lack of smut in recent months, an internal audit has revealed that a Jane Doe has been stealing each provised Library Scanner for Sigma Octantis. This has been rectified.
fix: Hey did you guys even notice that I put down more entertainment monitors instead of air alarms in the cafeteria and departures on Sigma like an idiot? That's fixed.
/:cl:
=> Sigma Octantis - Library Scanner; Air Alarms

local/code/modules/lewd/lewd_items/leash.dm, local/code/modules/lewd/verbs.dm
https://github.com/NovaSector/NovaSector/pull/2306
https://github.com/Skyrat-SS13/Skyrat-tg/pull/21287
Latter is good for player safety; former is good for code sanity. And the new bells and whistles.
:cl: softcerv for Skyrat, vinylspiders and unit0016 for Nova Sector
qol: adds a safeword verb under the ooc tab that can be used to remove all equipped organic interface items from someone.
code: Leashes have been heavily refactored and now come with additional features.
/:cl:
=> Backports NS Leash Refactor; SR OOC Escape

.github/CODEOWNERS
No player-facing changes. I'm targeting `/_maps/` rather than `/_maps/effigy/` specifically to account for repaths / new stuff upstream I'd have to take into consideration.
=> Adds myself as codeowner of /_maps/; fixes alphabetization

code/modules/modular_computers/file_system/programs/messenger/messenger_data.dm, code/modules/modular_computers/file_system/programs/messenger/messenger_program.dm, tgui/packages/tgui/interfaces/NtosMessenger/ChatScreen.tsx, tgui/packages/tgui/interfaces/NtosMessenger/types.tsx, tgui/packages/tgui/styles/interfaces/NtosMessenger.scss
Port, original PR: https://github.com/NovaSector/NovaSector/pull/1329
When you begin a PDA message with the "#" symbol, it is marked as "subtle" stopping it from being shown to ghost chats. For when you have something you REALLY wanna say but you only want a certain someone to see it. (unless your pda gets stolen, good luck explaining it then.)
A rigged message (PDA Bobm (spelt correctly)) will never be subtle, ever.
:cl: LordVoidron, vinylspiders
add: Private (no ghost) pda messaging, done by adding "#" to start of PDA message.
qol: Added button to NTOS messenger TGUI to toggle private messaging.
/:cl:
=> Subtle PDA messaging

_maps/effigy/map_files/SigmaOctantis/SigmaOctantis.dmm
:cl:
fix: The engineering console in the SMES room on Sigma Octantis is no longer... scuffed.
/:cl:
=> Sigma Octantis - Engineering SMES Fix

local/code/game/machinery/dna_fixer.dm
🆑 LT3
fix: DNA Fixer now provides better feedback whether the machine is turned on, or just a player sitting in there twiddling their thumbs idly while ghosts scream at the monitor that nobody turned it on
balance: Micro-laser tier now reduces DNA Fixer processing time at the expense of power
qol: DNA Fixer consent dialog moved to the start of procedure
qol: DNA Fixer automatically asks for consent after a delay
fix: Breaking out of the DNA Fixer doesn't render the machine permanently broken
balance: Breaking out of the DNA Fixer causes player damage
image: DNA Fixer now has sound and light, new icon states
/:cl:
=> Update DNA Fixer

code/__HELPERS/global_lists.dm, local/code/modules/bloopers/atoms_movable.dm, local/code/modules/bloopers/bark.dm, local/code/modules/bloopers/bark_list.dm
Upgrades the voice blooper system to support randomized sound selections for certain voice types, currently demo'd via the W.D. Gaster voice now being accurate.  This should lay the groundwork for a larger expansion allowing things like the Don't Starve vocal bloops to be properly randomized per their O.G. implementation.
The single W.D. Gaster bloop on repeat hurts my all-too Undertale-fanon-fixated SOUL.  Now it doesn't.  Being able to get the Don't Starve bloops working down the line should be a nice boost, too, they're really friggen charming.
https://github.com/effigy-se/effigy-se/assets/2958111/4e0fd27a-d381-4cae-a5d1-d9614a06aea6
:cl:
fix: The Gaster blooper voice is now accurate!
refactor: Multi-sound blooper voices are now supported.
/:cl:
=> Randomizable Blooper Support

local/code/modules/mob/living/silicon/robot/robot_model.dm
Fixes #853 
:cl:
fix: Cargo borgs can use their modules.
/:cl:
=> Stopgaps cargo borg icon

local/code/modules/mob/living/carbon/human/species_types/akula.dm
This doesn't apply to the more generalized Aquatics; JUST Akula.
:cl:
admin: Akula that pray get cable coil as their 'cookie'.
/:cl:
=> Akula that pray get cable coil

code/modules/mob/living/carbon/human/_species.dm, local/code/modules/mob/dead/new_player/sprite_accessories/genitals.dm, local/code/modules/surgery/organs/genitals.dm
Re-orders enterprise resource planning bodypart rendering to actually fit in underneath accessories & all clothing but undersuits, as was likely originally intended. I am open to trying to modify this code further to make layer an explicit toggle with a verb but it's gonna be Complicated(tm) to get right.
Amended to also change layers dependent on underclothes - with appropriate underclothes enabled, the layer shifts to 0.02 below undersuits (and underclothes now render at 0.01 below), allowing certain combinations on the chest to be viable. Without appropriate underclothes, they remain above the uniform layer (e.g, combo with gear harness, leg-only undersuits) as initially implemented.
Long hair over the chest, open jacket over the chest, the bespoke accessories, all of them *work now*! …
=> [MODULAR] Bodypart Layering Tweaks

_maps/effigy/map_files/RimPoint/RimPoint.dmm
:cl:
fix: Rimpoint's bridge is less scuffed; the doors cycle and there's now a secrecords console
/:cl:
=> Rimpoint: Everything But Cameras

local/code/modules/mapfluff/ruins/jungle_ruin_code.dm
Hey; did you know Luna's energy upgrade was borked to apply the esword stats to the *upgrade itself* rather than the sword?
I just found out. God; I feel stupid. Fixes it so that Luna is now mechanically all there.
See here how examining the stats actually. Works; now:
:cl:
fix: Luna's energy upgrade is no longer just cosmetic.
balance: To account for some fuckery with ESword balancing, an unupgraded version of Luna has higher unarmored wound chances but even lesser armor penetration and blockchance. The energy upgrade will trade the wound bonus for the stats of an esword.
/:cl:
=> [LOL] Unfucks Luna's Energy Upgrade So It Actually Works

code/modules/mob_spawn/ghost_roles/mining_roles.dm, code/modules/mob_spawn/mob_spawn.dm, local/code/controllers/subsystem/persistence.dm, local/code/modules/lewd/clothing_pref_check.dm, local/code/modules/lewd/lewd_items/shibari.dm, local/code/modules/mob_spawn/ghost_roles/mining_roles.dm, local/code/modules/mob_spawn/mob_spawn.dm
:cl: 00-Steven, FearfulFurnishing, dis-integrates-the-integration-tests for Nova Sector
fix: Fixed NIF persistence.
fix: fixes ghost roles sometimes being given random mutant body parts if no selection for the part was made
fix: Shock Collar is now properly recognized as a lewd item, and thus can be removed using the Remove verb.
qol: Shibari Rope stacks now fit in boxes.
/:cl:
=> Another Nova Sector Port Round

code/__DEFINES/_effigy/keybindings.dm, local/code/datums/components/pixel_shift_component.dm, local/code/datums/keybinding/mob.dm, local/code/modules/mob/living/living.dm
Adds the ability to pixelshift pulled items & tilt yourself; and optimizes pixelshifting code significantly. ALL codework within is by Odairu. This is a direct port with minimal, strictly spelling and phrasing related changes.
I'm counting this as a feature parity measure considering pixelshifting was grandfathered from skyrat.
:cl: Odairu for Skyrat 13
add: adds pixel shifting items, and pixel tilting mobs
code: optimizes pixelshifting
/:cl:
=> [PORT] Updated Pixelshifting From Skyrat

_maps/effigy/map_files/RimPoint/RimPoint.dmm, _maps/effigy/map_files/SigmaOctantis/SigmaOctantis.dmm, _maps/effigy/templates/condos/alleyway.dmm, _maps/effigy/templates/condos/beach_condo.dmm, _maps/effigy/templates/condos/dsthree_condo.dmm, _maps/effigy/templates/condos/foxhole_chapel.dmm, _maps/effigy/templates/condos/gm_condo.dmm, _maps/effigy/templates/condos/holestation_bridge.dmm, _maps/effigy/templates/condos/lodge_pool.dmm, _maps/effigy/templates/condos/manor_hall.dmm, _maps/effigy/templates/condos/medieval_bog.dmm, _maps/effigy/templates/condos/necropolis.dmm, _maps/effigy/templates/condos/northstar_dorms_four.dmm, _maps/effigy/templates/condos/ocean_view.dmm, _maps/effigy/templates/condos/planar_soil.dmm, _maps/effigy/templates/condos/sigma_lux_dorm.dmm, _maps/effigy/templates/condos/station_arrivals.dmm, _maps/effigy/templates/condos/xeno_resin.dmm, local/code/datums/loadouts/loadout_datum_neck.dm
:cl:
add: Sigma Octantis And Rimpoint have been spruced up more.
fix: Neck loadout items are selectable again.
fix: Space no longer bleeds into your planetside condo.
/:cl:
=> Fixes Neck Loadout Options & More Quarks

code/modules/mod/mod_control.dm
Restores unintentionally removed code that handled removing modsuits from your back. This along with the effigy edit above it can be removed in the next upstream merge as tg added a check for removing the suit when it's active, but for now this will solve the immediate problem.
Fixes #985
:cl:
fix: fixed being unable to remove modsuits from your back slot.
/:cl:
=> Fix modsuits being unremovable

_maps/effigy/map_files/RimPoint/RimPoint.dmm
:cl:
fix: The AI can now see the second floor of the library on Rimpoint. Additionally; newscasters have been spread around where they should've been.
/:cl:
=> Rimpoint - Library Cameras; Newscasters

_maps/effigy/map_files/SigmaOctantis/SigmaOctantis.dmm
:cl:
fix: Sigma Octantis no longer has a bin that just breaks the floor and does nothing else. Oops.
/:cl:
=> Sigma - Fixes The Medbay Bin + Adds More Holopads

code/modules/client/client_procs.dm, local/code/datums/keybinding/communication.dm
Fixes a bug wherein binding a combination hotkey that involves a key used in a communication hotkey causes both actions to trigger when the combination hotkey is pressed e.g. L on LOOC and CtrlL on *laugh causes you to both laugh and open the LOOC menu when you press CtrlL.
Bug fix, brings relevant code to parity with upstream (tg uses the `/datum/keybinding` overrides instead of the switch case in `client_procs.dm` now)
:cl:
fix: Fixes communication hotkeys conflicting with other hotkeys that use that button.
/:cl:
=> Fix communication hotkeys conflicting with all others

code/__DEFINES/_effigy/traits.dm, code/modules/jobs/job_types/detective.dm, local/code/datums/elements/unique_examine.dm, local/code/modules/library/skill_learning/job_skillchips/detective.dm
going back on being lazy; better do it now than later
:cl:
del: The functionality of the second detective skillchip has been moved into the first.
/:cl:
=> rolls both detective skillchips into one

_maps/effigy/map_files/SigmaOctantis/SigmaOctantis.dmm
Rotate the tank compressor in Sigma Octantis ordnance because it was backwards and didn't work
Gotta do those gas shells
:cl:
fix: the tank compressor in Sigma Octantis ordnance should work now.
/:cl:
=> Flip Sigma Octantis tank compressor turnways

local/code/game/objects/items/devices/summon_beacon.dm
Rewrite summoning beacons to use `ranged_interact_with_atom` because `afterattack` is no good anymore
Fixes #996 
:cl:
fix: fixed gas miner beacons not working.
/:cl:
=> Fix gas miner beacons

code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
Add a box with two gas miner beacons to the CE's locker.
🥺👉👈 (having these round start is really handy for Projects)
:cl:
add: The CE now starts with a box of two gas miner beacons in their locker.
/:cl:
=> Add box of gas miner beacons to CE's locker

_maps/effigy/map_files/FoxHoleStation/foxholestation.dmm, _maps/effigy/map_files/RimPoint/RimPoint.dmm, _maps/effigy/map_files/SigmaOctantis/SigmaOctantis.dmm
:cl:
add: Flatpacks have been added to all Effigy-specific maps. Oops.
/:cl:
=> Adds Flatpacks to each map roundstart

local/code/game/objects/structures/scrap.dm
the description for scrap piles incorrectly referenced their old loot pool (you have to remember salvaging is hacked together from a few different mechanics' shambling husks). this corrects that
:cl:
spellcheck: scrap no longer insinuates it contains ore.
/:cl:
=> [WEBEDIT] Changes scrap pile description
