- code/__DEFINES/_effigy/chat.dm
- code/controllers/subsystem/nightshift.dm
- packages/ux/announcements.dm
- tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
:cl: LT3
image: Station broadcasts no longer take up a stupid amount of screen space
/:cl:
> New alert notification spans

- _maps/map_files/MiniStation/MiniStation.dmm
:cl: LT3
fix: Fixed MiniStation burn chamber air alarm
/:cl:
> Update MiniStation air alarm

- code/modules/client/preferences.dm
- code/modules/client/preferences/clothing.dm
- code/modules/client/preferences/middleware/species.dm
- code/modules/client/preferences/underwear_color.dm
- code/modules/surgery/bodyparts/_bodyparts.dm
Fixes https://github.com/effigy-se/effigy-se/issues/51
> Fix body markings

- code/modules/mob/living/carbon/carbon_defense.dm
- packages/traits/neutral_traits.dm
- tgstation.dme
:cl: LT3
fix: Touch fluffy tail, slap marshmallow ass
/:cl:
> Fix ass slapping

- packages/donators/plushes.dm
Fixes the basetype not being updated properly.
Also also, please don't let this be a repeat of when SR donators found out that plushies could breed. I *still* remember how grossed out a handful got.
> Corrects a pathing issue with plushies

- packages/adv_medical/wounds/bones.dm
Missing arguments, nothing fancy
> Fixes the one Wound-Related VSC Error

- code/__HELPERS/global_lists.dm
Fixes https://github.com/effigy-se/effigy-se/issues/86
:cl: LT3
fix: Crafting menu now works
:/cl:
> Fix crafting menu

- packages/emotes/emote_panel.dm
- tgstation.dme
> Emote Panel

- code/modules/tutorials/tutorials/drop.dm
- code/modules/tutorials/tutorials/switch_hands.dm
Fuck off we know how to pick up and drop items.
> Disable Tutorial

- code/modules/mob/living/carbon/human/human_update_icons.dm
Fixes #91 
:cl: LT3
code: Fixed Vox belt slot causing runtime
/:cl:
> Fix Vox runtime

- code/__DEFINES/wounds.dm
- code/modules/client/preferences.dm
Fixes https://github.com/effigy-se/effigy-se/issues/93
> Fix Wound CI

- code/datums/keybinding/communication.dm
- tgui/packages/tgui-say/ChannelIterator.ts
- tgui/packages/tgui-say/styles/colors.scss
Makes LOOC and whisper compatible with the new TGUI Say 1.1 update
> TGUI Say Update v1.1 additions

- code/datums/mood_events/generic_negative_events.dm
- code/game/objects/structures/tables_racks.dm
- code/modules/surgery/surgery_step.dm
- packages/adv_medical/operatingtable.dm
- tgstation.dme
:cl: LT3
fix: Operating tables now apply numbing as expected
/:cl:
> Fix operating tables

- _maps/map_files/MiniStation/MiniStation.dmm
:cl: LT3
fix: Ministation now has spawn points for midround events
/:cl:
> Adds maint landmarks to Ministation

- code/game/machinery/doors/airlock.dm
:cl: LT3
code: Rapid airlocks: Now 20% faster!
/:cl:
> Airlocks: now 20% faster

- _maps/map_files/FoxHoleStation/foxholestation.dmm
HHHAH OOPS.
FIXES WEIRD DECALS, NAVIGATE DESTINATIONS, A FEW OTHER SMALL THINGS IT'S FINE.
> [FUCK] Absolutely WASTES This good branch name by fixing some small Foxhole Issues

- _maps/map_files/FoxHoleStation/foxholestation.dmm
few quick fixes to the SM room to add lights and shutter controls, plus removing stray shutter
:cl:
fix: Engineering goofs, lights, shutter controls, alarms. Plus stray rad shutter in the hallway
/:cl:
> There are many holes Ed Boy

- packages/adv_engineering/tools.dm
- tgstation.dme
:cl: LT3
balance: Experimental welder is now in the small weight class
qol: Experimental welder is now available in the science protolathe
/:cl:
> Welder changes

- packages/gfx/machinery.dm
I thought https://github.com/effigy-se/effigy-se/pull/182 merged. Oops.
> Fix APC sprites

- code/__DEFINES/economy.dm
- code/controllers/subsystem/economy.dm
- code/modules/mob/living/carbon/human/species_types/ethereal.dm
- code/modules/mob/living/carbon/human/species_types/felinid.dm
- code/modules/mob/living/carbon/human/species_types/flypeople.dm
- code/modules/mob/living/carbon/human/species_types/golems.dm
- code/modules/mob/living/carbon/human/species_types/jellypeople.dm
- code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
- code/modules/mob/living/carbon/human/species_types/mothmen.dm
- code/modules/mob/living/carbon/human/species_types/plasmamen.dm
- code/modules/mob/living/carbon/human/species_types/podpeople.dm
- packages/customization/modules/mob/living/carbon/human/species/akula.dm
- packages/customization/modules/mob/living/carbon/human/species/aquatic.dm
- packages/customization/modules/mob/living/carbon/human/species/dwarf.dm
- packages/customization/modules/mob/living/carbon/human/species/ghoul.dm
- packages/customization/modules/mob/living/carbon/human/species/humanoid.dm
- packages/customization/modules/mob/living/carbon/human/species/insect.dm
- packages/customization/modules/mob/living/carbon/human/species/lizard.dm
- packages/customization/modules/mob/living/carbon/human/species/mammal.dm
- packages/customization/modules/mob/living/carbon/human/species/placeholder_helper.dm
- packages/customization/modules/mob/living/carbon/human/species/podweak.dm
- packages/customization/modules/mob/living/carbon/human/species/skrell.dm
- packages/customization/modules/mob/living/carbon/human/species/tajaran.dm
- packages/customization/modules/mob/living/carbon/human/species/unathi.dm
- packages/customization/modules/mob/living/carbon/human/species/vox.dm
- packages/customization/modules/mob/living/carbon/human/species/vulpkanin.dm
- packages/customization/modules/mob/living/carbon/human/species/xeno.dm
- packages/synths/species/synthetic.dm
- packages/teshari/_teshari.dm
:cl: LT3
balance: Wealth redistribution. All races are now paid equally!
/:cl:
> Space Scandinavia

- _maps/foxholestation.json
OOOOPSSSS
:cl:
fix: Explosions now work right on foxhole.
/:cl:
> [FUCK] Fixes Foxhole Explosions

- _maps/map_files/FoxHoleStation/foxholestation.dmm
I miss the tweak CL tag.
:cl:
fix: Foxhole's broadcast studio has reached parity. Oops.
/:cl:
> Various Foxhole Tweaks, Patches, And Details

- packages/greyscale/greyscale_clothing.dm
- packages/loadouts/loadout_items/loadout_datum_neck.dm
- tgstation.dme
:cl: LT3
add: Added customisable cloak, veil, shroud, boatcloak
/:cl:
> Add greyscale neckwear

- _maps/map_files/FoxHoleStation/foxholestation.dmm
https://www.youtube.com/watch?v=vb2p_Q5v3nE
:cl:
fix: The Foxhole SM shutters work. Oops.
/:cl:
> [FUCK] Fixes Foxhole SM Shutters

- packages/liquids/liquid_systems/liquid_effect.dm
This shit is absolutely fucked and we need someone familiar with how the FUCK the rendering system works (call on coderbus?) to take a look to fix this for real. This does not ENTIRELY fix the issue with immutable liquids being fucked, there's still annoying 
✨ ✨ QUIRKY BLEEDTHROUGH ✨ ✨ 
But immutables at least render up here.
God.
This sucks.
See #213 for more on this garbage, and our pudgy attempts to work around it. In spite of the fact this object is entirely unused. I mean we could use it, I guess, but not like this. *NOT LIKE THISSSSSSSS*
> [FUCK] (Genuinely) Half-"Fixes" #213

- _maps/map_files/FoxHoleStation/foxholestation.dmm
See MapDiffBot.
:cl:
add: Foxhole has received a proper public mining shuttle.
/:cl:
> Foxhole Public Mining Shuttle, Misc Fixes

- _maps/effigy_liquids.json
> [FUCK] Disables Tot Unit Test On Liquids Debug

- _maps/effigy_liquids.json
- _maps/map_files/MiniStation/MiniStation.dmm
- packages/automapper/area_spawn_subsystem.dm
We just have flaky shit and an upstream issue left. I'm mad but whatever.
> [FUCK] (Gets Close To) Fixing Codebase CI

- code/modules/clothing/under/suits.dm
Fix https://github.com/effigy-se/effigy-se/issues/203
That one 'unknown' constantly on the crew monitor. Ugh.
:cl: LT3
del: Removed Pun Pun from the crew health monitor
/:cl:
> Hide the monke

- _maps/tramstation.json
- interface/skin.dmf
- local/interface/interface.dm
- tgstation.dme
Lost? Now you have a button!
:cl: LT3
add: Get lost slightly less often, WebMap button now at the top right!
/:cl:
> Add WebMap button

- _maps/map_files/FoxHoleStation/foxholestation.dmm
HOW DID THESE GET HERE...
:cl:
fix: The turf decals on foxhole should be marginally less scuffed. As in inside walls. I know.
/:cl:
> [FUCK] Cleans up Some FoxHole Turf Decals

- _maps/map_files/FoxHoleStation/foxholestation.dmm
- _maps/templates/automapper/metastation/metastation_broadcast_studio.dmm
:cl:
fix: They are in the walls they are in the walls they are-
/:cl:
> [FUCK] Fixes Some Dirt-On-Wall Action

- _maps/map_files/FoxHoleStation/foxholestation.dmm
Closes #251 
:cl:
fix: Foxhole has display cases for the curator now. Oops.
/:cl:
> [FUCK] Foxhole Display Cases

- _maps/map_files/FoxHoleStation/foxholestation.dmm
- packages/loadouts/loadout_items/loadout_datum_toys.dm
:cl:
add: The shark plushie is in the loadout. It's cute.
fix: Foxhole xenobio is usable. Oops.
/:cl:
> [FUCK] Fixes Foxhole Xenobio + Loadout Shark Plushie

- code/modules/asset_cache/assets/body_zones.dm
- tgui/packages/tgui/components/BodyZoneSelector.tsx
Fixes https://github.com/effigy-se/effigy-se/issues/151
> Surgery doll has cat ears

- _maps/map_files/FoxHoleStation/foxholestation.dmm
Oops.
:cl:
fix: Simplebots now actually do patrols on Foxhole. They still can't navigate z-levels.
fix: Consequently, Foxhole's Beepsky(s) is (are) real and can hurt you. One patrols maintenance on the second floor. I'm not joking.
/:cl:
> Foxhole - Simplebots Now Work.

- packages/modular_implants/code/nifs.dm
- packages/modular_implants/code/nifsofts.dm
- packages/modular_implants/code/nifsofts/money_sense.dm
- packages/modular_implants/code/nifsofts/prop_summoner.dm
- packages/modular_implants/code/nifsofts/soulcatcher.dm
- packages/modular_implants/code/soulcatcher/soulcatcher_body_component.dm
Kills off the little bit of `.proc/procname` leftover from me porting NIFs.
> PROC_REF (Helps Towards 515 Compat)

- _maps/map_files/FoxHoleStation/foxholestation.dmm
:cl:
qol: There are showers in foxhole medbay outside of virology now. Oops.
qol: There's also more AI holopads.
add: A handful of decals have been reworked on Foxhole.
qol: Foxhole Atmos has easier access to space, and some maint has been shaken up around it.
/:cl:
> Foxhole Quarks

- code/modules/power/lighting/light.dm
Fixes https://github.com/effigy-se/effigy-se/issues/290
> Make lights update appearance after icon_state change

- code/__DEFINES/_effigy/api.dm
- interface/skin.dmf
- local/code/datums/effigy_services.dm
- local/code/modules/client/effigy/bugreport.dm
- tgstation.dme
Create issue reports sent via Effigy API, no player interaction with Github required.
Player inputs title and issue, a ticket is created with collected round data.
:cl: LT3
refactor: The Report Issue button now makes it easy to report issues
/:cl:
> Effigy Report Issue button

- code/game/gamemodes/dynamic/dynamic_rulesets.dm
- code/game/gamemodes/dynamic/dynamic_rulesets_latejoin.dm
- code/game/gamemodes/dynamic/dynamic_rulesets_midround.dm
Fixes the antag button on the lobby splash screen
:cl: LT3
fix: Disabling antag on the lobby splash menu actually does something
/:cl:
> Disabling antag on the splash screen actually does something

- code/modules/surgery/bodyparts/head_hair_and_lips.dm
- html/changelogs/archive/2021-12.yml
- local/code/modules/client/preferences/genitals.dm
- tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/body_type.tsx
- tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/skin_tone.tsx
- tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/skyrat/genitals.tsx
- tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/species_features.tsx
:cl: LT3
fix: Genital color customization is back
/:cl:
> fix deez nuts

- code/datums/status_effects/debuffs/drunk.dm
- code/modules/reagents/chemistry/reagents/drinks/alcohol_reagents.dm
- code/modules/surgery/organs/internal/liver/_liver.dm
:cl: LT3
fix: Crew can now properly hold their alcohol
/:cl:
> Increased alcohol tolerance

- _maps/map_files/FoxHoleStation/foxholestation.dmm
:cl:
fix: Nanotrasen has been fined one (1) credit for improper fire safety on Foxhole. I sure hope somebody got fired for that blunder.
/:cl:
> Foxhole Wallmount Pass

- local/code/modules/client/preferences/genitals.dm
> Remove debug message from prefs menu

- _maps/map_files/FoxHoleStation/foxholestation.dmm
- _maps/map_files/MiniStation/MiniStation.dmm
Also some minuscule unlisted fixes and changes.
:cl:
add: The coroner has a half-real office on Ministation.
fix: Ian can actually have his birthday on Foxhole.
/:cl:
> Ministation - Coroner Gunk + Foxhole Ian Helpers

- local/code/modules/mob/living/carbon/human/species_types/roundstartslime.dm
Your honor, my client pleads oopsie daisies.
:cl:
fix: Slimepeople have their unique features back. Oops.
/:cl:
> Fixes Slimeperson Morphing + Toxins Affinity

- code/modules/power/cable.dm
Adds species specific cable handling
:cl: LT3
add: Do you know what day it is?
/:cl:
> Add Species based cable handler

- code/_globalvars/_effigy/config.dm
:cl: LT3
server: Effigy config keys now have defaults set
/:cl:
> Update default config entries

- _maps/shuttles/whiteship_foxhole.dmm
- local/code/datums/shuttles.dm
Come on, this is the one thing FoxHole was missing, you knew it was coming EVENTUALLY.
:cl:
add: Foxhole now has a matching whiteship, slightly expanding the possible pool just that little bit more. It's also pretty fuckin' cozy.
/:cl:
> Foxhole - Whiteship

- local/code/modules/client/preferences.dm
- local/code/modules/client/preferences_savefile.dm
- local/code/modules/research/designs.dm
:cl:
fix: Exploitable Information will now save, (but still can't be seen by anyone else.)
/:cl:
> Exploitable Info (Despite Being Unused) Will Now Save

- _maps/effigy_liquids.json
- _maps/map_files/FoxHoleStation/foxholestation.dmm
:cl:
add: Foxhole now has a public garden. Yeah. Yeah I know.
/:cl:
> Foxhole - Public Garden

- _maps/map_files/FoxHoleStation/foxholestation.dmm
:cl:
add: Railing should look more aesthetically pleasing on foxhole.
/:cl:
> Foxhole - Railing Endings

- code/modules/power/cable.dm
:cl:
balance: Teeth are no longer rubberized.
refactor: It's Friday, July 28th, 2023. I cannot elaborate on the significance of the week. I can elaborate that it is FIBRE OPTIC FRIDAY.
/:cl:
> Refactors Species Cable Handling

- _maps/map_files/FoxHoleStation/foxholestation.dmm
- _maps/map_files/MiniStation/MiniStation.dmm
:cl:
fix: Following an employee complaint - well, written on behalf of an employee - Foxhole And Mini now have proper lighting.
add: Ministation now has a convenient blockage to stop a certain someone from spacing the arrivals shuttle.
/:cl:
> Foxhole & Mini - Lighting Fix

- code/controllers/master.dm
> no sleep after init

- code/controllers/master.dm
- code/modules/client/preferences/species_features/mutants.dm
- tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/species_features.tsx
Closes https://github.com/effigy-se/effigy-se/issues/374
> Use tri-color only for mutant color

- _maps/map_files/FoxHoleStation/foxholestation.dmm
:cl:
fix: The Coroner now has their surgical bag on FoxHole.
/:cl:
> Minor Foxhole Touchups

- local/code/modules/mob/living/carbon/human/species_types/mammal.dm
:cl: LT3
fix: Fixed antenna selection on anthro species
/:cl:
> Fix antenna on anthro

- local/code/datums/loadouts/loadout_datum_neck.dm
:cl: LT3
add: Scryer is now available as a loadout item
/:cl:
> Adds scryer to loadout

- _maps/map_files/FoxHoleStation/foxholestation.dmm
:cl:
add: You can now actually ship crates on foxhole without getting a little silly... but the chute's in the disposals area, by the dorms. Better start walking.
/:cl:
> Foxhole - Disposals And Shipping

- _maps/map_files/FoxHoleStation/foxholestation.dmm
- _maps/shuttles/emergency_foxhole.dmm
yea
:cl:
fix: Foxhole is now back to being up to new standard.
/:cl:
> Foxhole - Turbine + Emergency Shuttle Modernization

- local/code/modules/lewd/lewd_chemistry/reagents/_aphrodisiac.dm
- local/code/modules/lewd/lewd_clothing/bdsm_mask.dm
- local/code/modules/mob/living/emotes/emotes.dm
- local/code/modules/modular_implants/nif_research.dm
balance pr lol
:cl: softcerv, tf-4, IAmGoofBall
balance: the evoker soulcatcher is now available through the R&D protolathe.
fix: Ass slapping now puts an overlay on the right person
fix: You cannot put enterprise resource planning drugs in the Odysseus syringe gun, and they will no longer be used in the random reagent recipes.
fix: fixes the organic interface gas mask not allowing for the wearer to inhale or exhale.
/:cl:
> Updates Some Of Our Ported Modules, Again

- _maps/map_files/FoxHoleStation/foxholestation.dmm
- _maps/map_files/RimPoint/RimPoint.dmm
- _maps/templates/automapper/birdshot/birdshot_cryo.dmm
- _maps/templates/automapper/icebox/icebox_cryo.dmm
- _maps/templates/automapper/metastation/metastation_cryo.dmm
- _maps/templates/automapper/northstar/northstar_cryo.dmm
- _maps/templates/automapper/tramstation/tramstation_cryo.dmm
- local/code/game/area/areas/station.dm
- tools/UpdatePaths/Scripts/Effigy Scripts/437_cryo.txt
> Cryo /area/ Path Fix

- _maps/RandomRuins/JungleRuins/deadorgone.dmm
- _maps/templates/automapper/automapper_config.toml
- _maps/templates/automapper/icebox/icebox_broadcast_studio.dmm
:cl:
fix: Icebox's laundry room is no longer incredibly broken, as is disposals.
fix: Dead Or Gone no longer creates atmosdiffs on roundstart.
/:cl:
> Icebox Broadcast Remap + Dead Or Gone Fix

- local/code/modules/client/preferences/genitals.dm
can't `initial()` on just raw paths
less runtime more word
nothing playerfacing
> Fix a runtime in character preferences

- config/maps.txt
- local/code/modules/liquids/ocean_flora.dm
No player-facing changes. Also mostly just an excuse so that I can see our updated CI status.
> Fixes One Non-CI Issue, And One CI Issue

- code/modules/unit_tests/unit_test.dm
Added some items from the skyrat ports to the uncreatables list that should never be created by unit tests as they simply do not function on their own (ie. the genitals base type)
less red X more code
nothing playerfacing
> Adds more items to the unit test uncreatable list

- code/modules/mob/dead/dead.dm
- local/code/modules/admin/effigy_tgs.dm
Gives a better status message if the game is waiting for players to hit ready.
:cl: LT3
qol: Status panel will tell you if the game is waiting for players to ready up
/:cl:
> Better indicator for pre-lobby wait

- _maps/map_files/RimPoint/RimPoint.dmm
:cl:
add: There are now more fuel tanks on rimpoint.
add: Every head of staff on Rimpoint now has a secret in their office, as was intended originally.
/:cl:
> rimpoint - more maint, more tanks, more secrets

- _maps/map_files/RimPoint/RimPoint.dmm
:cl: LT3
fix: Rimpoint's medbay elevator now has buttons, increasing usability by 400%
/:cl:
> Rimpoint medbay elevator buttons

- code/modules/modular_computers/computers/item/computer.dm
Does as it says on the tin
Longer rounds, no microwaves (yet)
:cl: LT3
qol: PDAs use slightly less power with the screen on
/:cl:
> Reduced PDA power consumption

- _maps/map_files/RimPoint/RimPoint.dmm
- code/modules/modular_computers/computers/item/computer.dm
Little tweaks to RimPoint medbay. Add bandages/mesh in the lobby, rotate a few windoors, add bandages to cargo/engineering.
:cl: LT3
add: RimPoint has been brought up to the latest Space OSHA standard, bandages now available in a few common areas.
/:cl:
> Update RimPoint with bandages

- _maps/map_files/RimPoint/RimPoint.dmm
This is the second time I've forgotten this stupid ass room. Guh!
:cl:
add: Rimpoint now has a public garden.
/:cl:
> Rimpoint - Public Garden

- SQL/database_changelog_effigy.md
- SQL/tgstation_schema.sql
- SQL/tgstation_schema_effigy.sql
- code/__DEFINES/subsystems.dm
- code/__HELPERS/logging/_logging.dm
- code/__HELPERS/roundend.dm
- code/controllers/subsystem/ticker.dm
- code/datums/helper_datums/getrev.dm
- code/game/world.dm
- code/modules/admin/IsBanned.dm
- code/modules/admin/sql_message_system.dm
- code/modules/discord/tgs_commands.dm
- code/modules/mod/modules/modules_general.dm
- local/code/controllers/subsystem/ticker.dm
- local/code/modules/admin/sql_ban_system.dm
- local/code/modules/admin/verbs/adminhelp.dm
- tgstation.dme
Puts the schema into the repo, increments the revision, fixes end of round report
:cl: LT3
fix: End of round report should properly broadcast to discord
code: Changed some log entries to use Effigy RID for consistency
server: Published Effigy DB schema
/:cl:
> Publish DB schema, fix end of round report

- code/game/turfs/closed/_closed.dm
Oops
:cl: LT3
fix: Thunderdome glass should no longer be a broken texture
/:cl:
> Unfuck thunderdome glass

- _maps/map_files/RimPoint/RimPoint.dmm
:cl:
fix: Rimpoint's Ordnance works again, the public garden has water, and the library has an elevator.
/:cl:
> Rimpoint  - Ordnance, Public Garden, Library Fixes

- _maps/effigy_liquids.json
> fix effigy liquids in the laziest way possible

- _maps/map_files/RimPoint/RimPoint.dmm
:cl:
add: Rimpoint now has a barsign. yea
/:cl:
> rimpoint barsign

- code/modules/mob/living/carbon/human/human_defense.dm
Reverts electric shocks to be in sync with TG.
Continued cleanup of ported edits.
:cl: LT3
balance: Reverted electric shock damage to match TG.
/:cl:
> Revert electric shocks to TG

- code/modules/mob_spawn/mob_spawn.dm
- local/code/modules/mob_spawn/mob_spawn.dm
- tgstation.dme
Tin
This was shockingly easy 
:cl:
add: You can now spawn in as ghost roles as your selected character
/:cl:
> Allows ghost role static spawning

- local/code/modules/surgery/robot_healing.dm
:cl: nikothedude for Skyrat 13
fix: Experimental robotic tend wounds now actually shows up
/:cl:
> Ports a Fix To The Issue Of All Time

- local/code/game/machinery/doors/firedoor.dm
- local/code/game/machinery/light.dm
TG lighting changes have made things a little dim with our lights having less range. Boosts light power to get to those dark corners without looking flat/fullbright.
:cl: LT3
code: Boosted light intensity, slightly reduced light range. This should improve overall lighting since upstream changes
/:cl:
> Adjust light intensity/range

- code/__DEFINES/_effigy/reagents.dm
- code/modules/mapfluff/ruins/spaceruin_code/oldstation/oldstation_fluff.dm
- code/modules/reagents/reagent_containers/cups/_cup.dm
- local/code/modules/reagents/reagent_containers/hypospray.dm
Syncs beaker code back with TG
:cl: LT3
balance: Beaker capacity is back to TG default
/:cl:
> Sync beakers to TG

- _maps/map_files/RimPoint/RimPoint.dmm
> [HALLOWEEN EVENT BRANCH] Rimpoint Compat. Layer

- code/controllers/subsystem/dbcore.dm
> SQL schema check

- code/modules/reagents/reagent_containers/cups/_cup.dm
:cl: LT3
fix: Large beakers actually hold 100u again
/:cl:
> Fix large beakers

- code/__DEFINES/_effigy/security_alerts.dm
- code/__DEFINES/_effigy/span.dm
- code/_globalvars/_effigy/config.dm
- code/controllers/subsystem/shuttle.dm
- code/modules/admin/verbs/playsound.dm
- local/code/controllers/subsystem/security_level.dm
- local/code/datums/level_datums.dm
- local/code/game/machinery/doors/airlock_override.dm
- local/code/modules/events/ev_meteors.dm
- tgui/packages/tgui/interfaces/CommunicationsConsole.js
> Fix magenta spans

- local/code/modules/holiday/holidays.dm
- tgstation.dme
Adds Effigy's birthday to the holiday greetings, the day it was forked from /tg/Station at commit https://github.com/effigy-se/effigy-se/commit/45af4e26f32b421f90d261f96950aa2a2c3caa24
:cl: LT3
add: Add holiday text for Effigy's birthday
/:cl:
> Add Effigy's birthday

- code/game/machinery/doors/airlock.dm
Revert removal of a nonmodular change to airlock sound frequency
:cl: LT3
sound: Airlock sounds again have a consistent frequency
/:cl:
> Remove varied frequency from airlock sound

- tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
- tgui/packages/tgui/constants.ts
Swaps medical and centcom radio colours, they were backwards in the other PR.
You won't notice before compile
> Swap backwards medical/centcom radio

- code/controllers/master.dm
Updates error message during init to provide more information
:cl:
/:cl:
> Update initialization error message

- code/__DEFINES/_effigy/security_alerts.dm
- code/_globalvars/_effigy/config.dm
- code/controllers/subsystem/shuttle.dm
- code/game/machinery/computer/communications.dm
- code/game/machinery/defibrillator_mount.dm
- code/modules/antagonists/cult/cult_items.dm
- code/modules/transport/elevator/elev_panel.dm
- local/code/controllers/subsystem/security_level.dm
- local/code/datums/level_datums.dm
- local/code/game/machinery/doors/airlock_override.dm
- local/code/modules/events/ev_meteors.dm
- tgui/packages/tgui/interfaces/CommunicationsConsole.jsx
Standardises security alert level colors with other servers
:cl: LT3
balance: Station now adheres to NT galaxy wide standardised alert level colours
/:cl:
> Remap alert level colours

- local/code/datums/loadout_manager.dm
- tgui/packages/tgui/interfaces/LoadoutManager.tsx
Fixes loadout menu for React port
:cl: LT3
fix: You should be able to change loadout items again
/:cl:
> Fixes loadout menu

- local/code/modules/client/preferences/scaling_method.dm
- tgui/packages/tgui/components/Dropdown.tsx
- tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/scaling_method.tsx
Early mirror of https://github.com/tgstation/tgstation/pull/80464
> Fixes dropdowns not rendering the selection's displayText post-selection (#80464)

- code/modules/discord/tgs_commands.dm
- local/code/controllers/subsystem/statpanel.dm
Adds active/observing counts to the statpanel and TGS
:cl: LT3
add: Statpanel and TGS now show active and observing players
/:cl:
> Split player counts on statpanel

- local/code/modules/admin/verbs/adminhelp.dm
> Fix adminhelp div

- local/code/modules/client/preferences/chat_color.dm
> Expand chat colour selection range

- code/__DEFINES/_effigy/chat.dm
- code/modules/mob/living/living_say.dm
- code/modules/unit_tests/say.dm
Adds auto-punctuation to the end of chat messages.
:cl: LT3
add: Auto-punctuation at the end of chat messages
/:cl:
> Chat auto-punctuation

- code/_globalvars/_effigy/subsystem.dm
- local/code/controllers/subsystem/dbcore.dm
- local/code/controllers/subsystem/effigy/effigy_services.dm
I made a mistake with how MariaDB works.
> EVID hotfix

- code/_globalvars/configuration.dm
- code/world.dm
- config/motd.txt
> Effigy branding

- local/code/datums/character_directory.dm
:cl: LT3
fix: Character directory no longer bluescreens when clicking borgs
/:cl:
> Fix character directory for cyborgs

- local/code/modules/client/preferences/chat_color.dm
Slight changes to how the bounds for custom text colors are set.
None
> Chat color processing tweaks

- _maps/map_files/FoxHoleStation/foxholestation.dmm
:cl:
fix: FoxHoleStation - the bridge is wheelchair accessible now. lol
/:cl:
> Fixes THAT Foxhole Elevator

- code/_globalvars/_effigy/config.dm
- code/controllers/subsystem/ticker.dm
- local/code/modules/lobby_music/lobby_music.dm
- tgstation.dme
Adds internet sound capability to lobby music. v1 is for a single track only.
:cl: LT3
add: Press any key to start
/:cl:
> Lobby music v1

- .gitignore
- code/__DEFINES/_effigy/ticker.dm
- code/controllers/master.dm
- code/controllers/subsystem/ticker.dm
- code/modules/admin/verbs/server.dm
- config/effigy_splash_fluff.txt
- local/code/controllers/subsystem/ticker.dm
- local/code/modules/mob/dead/dead.dm
- tgstation.dme
Enhancements to lobby music, game ticker.
:cl: LT3
add: New crew manifest announcement
code: Delayed game start will now give players time to ready up before starting
/:cl:
> Lobby screen/music v1.1 [SS Skip]

- code/modules/mob/living/carbon/human/_species.dm
- local/code/modules/mob/living/human/species.dm
Fixes https://github.com/effigy-se/effigy-se/issues/606
:cl: LT3
fix: Felinids should be able to select tails again
/:cl:
> Fix felinid tail selection

- code/__DEFINES/_effigy/DNA.dm
- code/__DEFINES/_effigy/mobs.dm
- code/__HELPERS/_effigy/global_lists.dm
- local/code/modules/client/preferences.dm
- local/code/modules/mob/living/carbon/human/species.dm
- local/code/modules/mob/living/carbon/human/species_types/aquatic.dm
- local/code/modules/mob/living/carbon/human/species_types/ghoul.dm
- local/code/modules/mob/living/carbon/human/species_types/humanoid.dm
- local/code/modules/mob/living/carbon/human/species_types/insect.dm
- local/code/modules/mob/living/carbon/human/species_types/lizard.dm
- local/code/modules/mob/living/carbon/human/species_types/mammal.dm
- local/code/modules/mob/living/carbon/human/species_types/monkey.dm
- local/code/modules/mob/living/carbon/human/species_types/moth.dm
- local/code/modules/mob/living/carbon/human/species_types/podweak.dm
- local/code/modules/mob/living/carbon/human/species_types/roundstartslime.dm
- local/code/modules/mob/living/carbon/human/species_types/skrell.dm
- local/code/modules/mob/living/carbon/human/species_types/synthetic.dm
- local/code/modules/mob/living/carbon/human/species_types/tajaran.dm
- local/code/modules/mob/living/carbon/human/species_types/unathi.dm
- local/code/modules/mob/living/carbon/human/species_types/vox.dm
- local/code/modules/mob/living/carbon/human/species_types/vulpkanin.dm
- local/code/modules/mob/living/carbon/human/species_types/xeno.dm
:cl: vinylspiders, LT3
fix: Schrodinger's digi leg prefs are now consistently applied
/:cl:
> Changes default_mutant_bodyparts list to be index based

- local/code/modules/mob/living/carbon/carbon_defense.dm
- tgstation.dme
Fixes https://github.com/effigy-se/effigy-se/issues/679
:cl: LT3
fix: Fixed slapping asses and pulling tails. Mrow.
/:cl:
> Fix big (ass) slappy

- tgui/packages/tgui/interfaces/PreferencesMenu/Effigy/CharacterPreferenceWindow.tsx
> React CharacterPreferenceWindow

- tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/base.tsx
> Fixes FeatureValueInput

- local/code/game/objects/items/devices/summon_beacon.dm
- local/code/modules/cargo/packs/adv_crates.dm
- tgstation.dme
Ports gas miner beacons from SR/Nova
:cl: LT3
add: Added gas miner beacons
/:cl:
> Gas miner beacons

- code/__DEFINES/colors.dm
- local/code/_onclick/hud/rendering/render_plate.dm
- local/code/game/machinery/doors/firedoor.dm
- local/code/game/machinery/light.dm
- tgstation.dme
Adjusts some lighting, default lighting is slightly brighter, less purple. Firedoors have larger impact on environment. Saturation shift away from green towards blue/purple.
:cl: LT3
refactor: Lighting adjustments to fixtures, firedoors, fire lighting
/:cl:
> Lighting adjustments (fixtures/firedoors/fire lighting)

- local/code/controllers/subsystem/ticker.dm
- local/code/modules/mob/dead/dead.dm
- local/code/modules/splash/ss_splash.dm
Moves fluff from SSticker to SStitle
Nothing player facing
> Loading screen fluff update

- _maps/map_files/SigmaOctantis/SigmaOctantis.dmm
- local/code/modules/plumbing/plumbers/destroyer.dm
- tgstation.dme
:cl:
add: Sigma's Chemical Disposers have received massive buffs. Good luck flooding it now, suckers.
/:cl:
> Sigma - Flood Prevention

- _maps/map_files/SigmaOctantis/SigmaOctantis.dmm
> Sigma - Airlock Fixes

- _maps/map_files/SigmaOctantis/SigmaOctantis.dmm
> Sigma - Generic Maint Landmarks

- tgui/packages/tgui-say/styles/content.scss
- tgui/packages/tgui/interfaces/NtosVirtualPet.tsx
- tgui/packages/tgui/styles/components/Dialog.scss
- tgui/packages/tgui/styles/components/Input.scss
- tgui/packages/tgui/styles/interfaces/NtosNotepad.scss
- tgui/packages/tgui/styles/layouts/NtosWindow.scss
Nothing player facing before compile
> Virtual Pet TGUI adjustments

- code/game/world.dm
Fixes all logs saving in the same folder when testing locally
:cl: LT3
fix: Fixed logging directory structure for local testing
/:cl:
> Fix local logging directory

- tgui/packages/tgui/interfaces/PreferencesMenu/LimbsPage.tsx
> Update emissives description

- local/code/controllers/subsystem/autotransfer.dm
> Better autotransfer logging

- _maps/map_files/SigmaOctantis/SigmaOctantis.dmm
- _maps/map_files/generic/CentCom_z2_effigy.dmm
- _maps/shuttles/interlink_blaster.dmm
- local/code/modules/shuttle/interlink.dm
see #751 for most of this, this encapsulates some minor fixes and yaddayadda.
> Minor Interlink Bumpdate

- code/modules/mob/living/carbon/human/_species.dm
- code/modules/mob/living/carbon/human/human_update_icons.dm
- local/code/modules/client/preferences/middleware/limbs_and_markings.dm
As it says on the tin
:cl: LT3
fix: The sector's strategic supply of digitigrade socks has been located
/:cl:
> Fix digi socks being invisible

- tgui/packages/tgui/components/SideDropdown.tsx
Fixes a little TGUI bug on the character prefs screen
> Update SideDropdown placement

- tgui/packages/tgui/interfaces/PreferencesMenu/Effigy/CharacterPreferenceWindow.tsx
> Update Character Preference window

- _maps/map_files/generic/CentCom_z2_effigy.dmm
- _maps/shuttles/interlink_blaster.dmm
- local/code/datums/weather/weather_types/rain_storm.dm
:cl:
fix: You will no longer psionically know when rain is coming.. when indoors. While outside, you can now understand what clouds converging means.
/:cl:
> Interlink + Rain Patches

- code/modules/mob/dead/new_player/new_player.dm
- local/code/modules/mob/dead/new_player/new_player.dm
- local/code/modules/splash/new_player.dm
- tgstation.dme
Logs toggling of the player ready status
> Ready status logging

- _maps/map_files/SigmaOctantis/SigmaOctantis.dmm
- html/changelogs/archive/2024-03.yml
- local/code/modules/transport/tram_controller.dm
- local/code/modules/transport/tram_controls.dm
- local/code/modules/transport/tram_displays.dm
- local/interface/interface.dm
- tgui/packages/tgui/interfaces/TramControl.tsx
Adds the webmap for Sigma Octantis, fixes spelling in some areas.
> Sigma Octantis webmap

- code/controllers/subsystem/statpanel.dm
- local/code/controllers/subsystem/statpanel.dm
Adds game server ping in addition to TGUI ping
> Statpanel update

- local/code/modules/client/preferences/subtle.dm
- local/code/modules/mob/living/emote.dm
- tgstation.dme
- tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/effigy/subtle.tsx
Port of https://github.com/Bubberstation/Bubberstation/pull/881 / https://github.com/Bubberstation/Bubberstation/pull/752
🆑 Majkl-J
qol: Subtler sound can now be toggled in game prefs
/:cl:
> Subtle notification sound

- code/modules/surgery/organs/organ_movement.dm
:cl: LT3
fix: You can now pick up organs off the floor
/:cl:
> Organs no longer glued to the floor

- _maps/map_files/RimPoint/RimPoint.dmm
:cl:
add: Rimpoint's roofs have been all prettied up! ...Sans the dorms'.
/:cl:
> Rimpoint - Roofs

- local/code/datums/ruins/jungle.dm
- local/code/modules/liquids/ocean_ruins.dm
> ruin datum name consistency patch

- _maps/effigy/map_files/SigmaOctantis/SigmaOctantis.dmm
:cl:
fix: Sigma now has cargo buttons.
fix: Sigma now has AI Sat Turret controls.
/:cl:
> Sigma Cargo + AI Sat Fixes

- local/code/modules/client/preferences/_preference.dm
This lets any species use any bodypart (horns, snouts, tails, etc).
More character customization.
:cl:
add: All mutant bodyparts are now available no matter your species.
/:cl:
> [READY] Allows all species to use all bodyparts.

- local/code/game/machinery/doors/firedoor.dm
> Firelock water sensor adjustment

- local/code/modules/client/preferences/erp_preferences.dm
> Update interaction preferences

- _maps/effigy/RandomRuins/OceanRuins/ocean_bubble_rally.dmm
- _maps/effigy/map_files/FoxHoleStation/foxholestation.dmm
- _maps/effigy/map_files/RimPoint/RimPoint.dmm
- _maps/effigy/map_files/SigmaOctantis/SigmaOctantis.dmm
- local/code/game/turfs/open/planet.dm
- tgstation.dme
:cl:
fix: Various little things are fixed on all three of the Effigy maps.
/:cl:
> Foxhole, Rimpoint, Sigma Fixes

- .github/alternate_byond_versions.txt
- .tgs.yml
- dependencies.sh
Updates component versions in CI workflow
> Update CI dependencies

- code/modules/mod/mod_control.dm
- local/code/modules/mob/living/carbon/human/human.dm
- local/code/modules/mob/living/emotes/turf_emote.dm
Fixes https://github.com/effigy-se/effigy-se/issues/801
> One Idiot Tries to Fix the OpenDream-Specific Lints

- code/modules/research/techweb/all_nodes.dm
- local/code/game/machinery/dna_fixer.dm
Replaces instances of Healixir with its internal name DNA Fixer, which is more apparent what it does.
:cl: LT3
spellcheck: Healixir is now consistently named DNA Fixer
/:cl:
> Rename Healixir to DNA Fixer

- dependencies.sh
- tgui/.prettierignore
- tools/bootstrap/node
- tools/bootstrap/node_.ps1
Enables both Node 14 and Node 20, TG PR 82334
None
> Creates a node compatibility mode (#82334)

- _maps/effigy/map_files/FoxHoleStation/foxholestation.dmm
- _maps/effigy/map_files/SigmaOctantis/SigmaOctantis.dmm
- local/code/modules/liquids/ocean_turfs.dm
> Upkeep: SMES Units

- code/game/machinery/computer/crew.dm
- code/modules/clothing/under/_under.dm
- tgui/packages/tgui/interfaces/CrewConsole.tsx
- tgui/packages/tgui/interfaces/CrewConsoleEffigy.tsx
https://github.com/NovaSector/NovaSector/pull/2603
https://github.com/tgstation/tgstation/pull/83348
:cl:
add: Added an EMP effect to sensors to scramble what the crew monitor sees
qol:  Crew monitor changes
/:cl:
> Crew Monitor

- _maps/effigy/map_files/RimPoint/RimPoint.dmm
- _maps/effigy/map_files/SigmaOctantis/SigmaOctantis.dmm
- local/code/game/objects/structures/plaques/static_plaques.dm
:cl:
add: Research now has it's own fax machine on Sigma Octantis.
/:cl:
> Sigma & Rimpoint - Minor Tweaks

- local/code/modules/mapfluff/ruins/jungle_ruin_code.dm
Closes #863 
:cl:
fix: Luna now ACTUALLY takes on the stats of an esword. Whoopsies. Teehee.
/:cl:
> Fixes Luna

- local/code/datums/weather/weather_types/rain_storm.dm
We may have multiple FUCK issue reports; but baby; it's raining outside.
:cl:
add: Rain now makes you wet. Watch out if you're a slime!
/:cl:
> You can now get wet.

- local/code/modules/reagents/reagent_containers/hypospray.dm
🆑 LT3
fix: Fixed 'fixes the large hypospray' not fixing the large hypospray
/:cl:
> Fixes large hypospray

- local/code/game/area/areas/mining.dm
> Fixes Rimpoint Double Ambience Define

- _maps/effigy/map_files/FoxHoleStation/foxholestation.dmm
- _maps/effigy/map_files/RimPoint/RimPoint.dmm
- _maps/effigy/map_files/SigmaOctantis/SigmaOctantis.dmm
- _maps/effigy/templates/automapper/birdshot/birdshot_broadcast_studio.dmm
- _maps/effigy/templates/automapper/icebox/icebox_broadcast_studio.dmm
- _maps/effigy/templates/automapper/metastation/metastation_broadcast_studio.dmm
- _maps/effigy/templates/automapper/northstar/northstar_broadcast_studio.dmm
- _maps/effigy/templates/automapper/tramstation/tramstation_broadcast_studio.dmm
- local/code/game/machinery/computer/camera.dm
> Fix map lints (telescreen)

- _maps/effigy/RandomRuins/JungleRuins/caves_trilogy_research.dmm
- _maps/effigy/map_files/RimPoint/RimPoint.dmm
- _maps/effigy/map_files/SigmaOctantis/SigmaOctantis.dmm
- local/code/datums/mapgen/Cavegens/JungleCaves.dm
- local/code/game/area/areas/mining.dm
- local/code/modules/mining/abandoned_crates.dm
- local/code/modules/modular_implants/nifsofts/prop_summoner.dm
- local/code/modules/vending/games.dm
- tgstation.dme
Backported versions of the improvements made to Rimpoint and Sigma Octantis for the collab.
:cl:
add: Rimpoint's perma has been reworked.
/:cl:
> Bubber Backports

- _maps/effigy/map_files/RimPoint/RimPoint.dmm
- local/code/modules/plumbing/plumbers/destroyer.dm
:cl:
fix: Nukies can now dock on Rimpoint.
fix: Sigma Octantis can now properly drain liquids that aren't water and ice. Oops.
/:cl:
> Fixes Rimpoint Not Having Nukie Docks; Sigma's Plumbing

- _maps/effigy/map_files/SigmaOctantis/SigmaOctantis.dmm
Guess what fuckin' idiot forgot medbay's liquid scrubbers
> OOPS - Sigma Medbay Plumbing Quickfix

- _maps/effigy/map_files/SigmaOctantis/SigmaOctantis.dmm
:cl:
fix: A bunch of medbay has been shuffled around on Sigma.
/:cl:
> Sigma - Medbay Shuffling

- _maps/effigy/map_files/SigmaOctantis/SigmaOctantis.dmm
- local/code/modules/liquids/ocean_areas.dm
:cl:
fix: For gameplay purposes, a lot of immutable liquid turfs on Sigma have been tightened up or exchanged for normal variants.
/:cl:
> Sigma - Liquid Consistency

- _maps/effigy/map_files/SigmaOctantis/SigmaOctantis.dmm
:cl:
add: Floods should be slightly easier on Sigma
/:cl:
> Sigma - Lossy Liquids

- _maps/effigy/map_files/RimPoint/RimPoint.dmm
I forgor
:cl:
add: Rimpoint's psychologist now actually has privacy. Oops.
/:cl:
> Rimpoint Psych Curtains

- _maps/effigy/map_files/RimPoint/RimPoint.dmm
I got distracted thinking of trying to fix the solarlight cameras not working. Guh
> FUCK - Rimpoint Medbay Cameras

- code/game/machinery/doors/door.dm
doors broken mrrrow
:cl:
fix: Normal doors can be opened again.
/:cl:
> Fix normal doors not opening

- local/code/modules/client/preferences/chat_color.dm
TG defined CM_CHAT_COLOR for something else now, so it screws with our use of the same define.
> Update runechat color defines

- _maps/effigy/map_files/SigmaOctantis/SigmaOctantis.dmm
:cl:
fix: Sigma Octantis' disposal network now works.
/:cl:
> Sigma Octantis - Disposal Fix

- code/__DEFINES/_effigy/research/techweb_nodes.dm
- local/code/game/objects/items/scythes.dm
- local/code/modules/research/techweb/all_nodes.dm
- tgstation.dme
:cl:
fix: Robotic Tend Wounds no longer costs enough points to make Illegal Tech blush.
/:cl:
> Effigy Techweb Pass

- _maps/effigy/map_files/FoxHoleStation/foxholestation.dmm
- _maps/effigy/map_files/RimPoint/RimPoint.dmm
Recent mirrors scuffed these; just fixing them
> turret control pass

- local/code/game/area/areas/mining.dm
:cl:
fix: Hotsprings will no longer have their music cut off early.
/:cl:
> Fix hotspring ambience

- _maps/effigy/map_files/RimPoint/RimPoint.dmm
Generally just makes Rimpoint a bit friendlier to navigate as an outsider.
:cl:
add: Rimpoint's exterior areas have been spruced up again.
/:cl:
> Rimpoint - Medical Extinguishers; Fireclosets, Emclosets; More Signange

- tgui/packages/tgui/interfaces/NifPanel.jsx
- tgui/packages/tgui/interfaces/NifSoulPoem.jsx
- tgui/packages/tgui/interfaces/NtosNifsoftCatalog.jsx
:cl: SomeRandomOwl, VinylSpiders for Nova Sector
fix: NIFsoft settings panel now works once again
/:cl:
> NIF TGUI Maintenance

- _maps/effigy/map_files/RimPoint/RimPoint.dmm
- _maps/effigy/map_files/SigmaOctantis/SigmaOctantis.dmm
- local/code/controllers/subsystem/mapping.dm
- local/code/datums/weather/weather_types/rain_storm.dm
- local/code/game/objects/effects/decals/turfdecal/markings.dm
- local/code/game/objects/effects/decals/turfdecal/tilecoloring.dm
- local/code/game/turfs/closed/minerals.dm
- local/code/game/turfs/open/water.dm
- local/code/modules/liquids/reagents/chemistry/reagents.dm
- local/code/modules/reagents/chemistry/reagents/other_reagents.dm
:cl:
add: Rimpoint's caves now have a river system!
fix: The entire cavern system on Rimpoint is no longer comedically water soluble
balance: water turfs will now delete liquids that flow onto them. IK. It's weird when I say it too
balance: By default; all reagents will evaporate when shallow enough in liquid form.
/:cl:
> Rimpoint: Underground Rivers, Further Detailed Exterior; Rain Fixes, & Liquid Nerfs

- local/code/datums/weather/weather_types/rain_storm.dm
no notable player-facing changes
> Rewrites Rimpoint's weather checks and converts spans

- _maps/effigy/RandomRuins/JungleRuins/caves_old_science.dmm
- _maps/effigy/map_files/RimPoint/RimPoint.dmm
Does the one thing I said I wouldn't do.
Rimpoint now has PATHWAYS. Lightning crackle
Dorms is missing it on purpose; everywhere else has stone intermingling with the former entirely dirt pathways
:cl:
add: Rimpoint's infrastructure budget has been increased massively; paving the way - get it - for roads.
/:cl:
> Rimpoint - Honest To God Infrastructure

- _maps/effigy/map_files/FoxHoleStation/foxholestation.dmm
:cl:
add: Part of maintenance on Foxhole has been reworked and is no longer a dead end.
add: FoxHole's maintenance access has been tweaked slightly; for cargo and security.
add: FoxHole's xenobio department has been reworked slightly.
/:cl:
> FoxHole: Misc Changes And Fixes

- .github/workflows/update_tgs_dmapi.yml
It's the wrong branch name gromit
> Fix Update TGS DMAPI Action Failing

- local/code/modules/client/preferences/_preference.dm
Port https://github.com/Bubberstation/Bubberstation/pull/1566
Need my genders
:cl:
add: Added two new options to character directory gender
/:cl:
> Port some new genders

- code/datums/world_topic.dm
early mirror of https://github.com/tgstation/tgstation/pull/88367 - secvulns are bad mmkay
> [s] ensure key config is set for any secure request

- code/modules/holiday/holidays.dm
Mirroring TG
:cl: LT3
balance: Xmas week has been extended to start at 18 December, get your jollymaxxing on
/:cl:
> Move Xmas to start on 18 Dec

- code/__DEFINES/_effigy/examine_defines.dm
- local/code/game/objects/items/storage/fancy.dm
- local/code/game/objects/items/toys.dm
- local/code/modules/cards/deck/deck.dm
- local/code/modules/mob/living/brain/MMI.dm
- tgstation.dme
:cl:
code: Adjusted standards for Examine++; with defines for antagonist groups being the go-to.
/:cl:
> E++ - A Few More Descriptions; Futureproofing

- code/__DEFINES/_effigy/examine_defines.dm
- local/code/game/objects/items/storage/fancy.dm
- local/code/game/objects/items/toys.dm
- local/code/modules/cards/deck/deck.dm
- local/code/modules/mob/living/brain/MMI.dm
> [FUCK] CI Fix

- .github/workflows/ci_suite.yml
Cherry pick https://github.com/tgstation/tgstation/pull/88988 to fix check failures in #1006
> Adds a .NET 9 SDK setup action to linters (#88988)

- _maps/effigy/map_files/RimPoint/RimPoint.dmm
- local/code/game/area/areas/mining.dm
- local/code/game/area/areas/station/ai_monitored.dm
- local/code/game/area/areas/station/command.dm
- tgstation.dme
:cl:
add: The AI Sat has been redone on Rimpoint.
add: The HoP line on rimpoint has been moved indoors for a photobooth.
add: Telecomms has been made full-sized on Rimpoint.
/:cl:
> [Rimpoint] AI Satellite; HoP Line; Telecomms Rework

- local/code/game/objects/effects/spawners/random/clothing.dm
- local/code/modules/lewd/lewd_clothing/bdsm_mask.dm
- local/code/modules/lewd/lewd_clothing/shockcollar.dm
:cl:
fix: A very specific gasmask is back in a very specific vendor.
/:cl:
> Fixes #862

- code/modules/admin/view_variables/debug_variable_appearance.dm
Port https://github.com/tgstation/tgstation/pull/86579
Having to downgrade BYOND every time I want to compile this codebase makes me sad
> Fix compile errors on BYOND versions > 515.1642

- local/code/modules/clothing/neck/collars.dm
- local/code/modules/lewd/lewd_clothing/kink_collars.dm
- local/code/modules/lewd/lewd_clothing/shockcollar.dm
backports https://github.com/NovaSector/NovaSector/pull/4188 ; which fixes all the issues collars had here.
:cl: FlufflesTheDog for Nova Sector
qol: Collars use pen renaming, which also let you change their description
fix: keys can actually be used on collars
fix: shock collars no longer turn invisible when enabled/disabled
/:cl:
> Backports Nova Sector #4188
